services:
  mysql:
    container_name: e-commerce_db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=root
      - MYSQL_PASSWORD=admin
    ports:
      - 3306:3306
